name: cosypose
channels:
   - conda-forge
   - pytorch
dependencies:
  - python=3.10.4
  - pinocchio=2.6.18
  - urdfdom=3.1.1
  - assimp=4.1.0  # dkushn: seems it is not required
  - rclone=1.52.3
  - gxx_linux-64=7.3.0
  - git-lfs=2.13.3
  - ffmpeg=4.2
  - bzip2=1.0.8
  - git>=2.34.1
  - cmake>=3.14.0
  - pip=23.0.1
  - numpy=1.22.3
  - pillow=9.4.0
  - ipython
  - pip:
      - ./deps/job-runner
      - torch
      - torchvision
      - pybullet
      - imageio==2.28.1
      - simplejson==3.19.1
      - opencv-python==4.1.2.30 # not used
      - opencv-contrib-python==4.4.0.42 # not used
      - torchnet==0.0.4
      - tqdm==4.65.1
      - lxml==4.4.2 # not required
      - transforms3d==0.4.1
      - distributed==2.9.1 # not required
#      - joblib==0.14.1
      - joblib==1.2.0 # dkushn: TODO requires validation
      - pandas==2.0.1 # required update for python 3.10
      - xarray==2023.5.0 # required for pandas
      - pyarrow==0.15.1 # not required
      - matplotlib==3.7.1 # dkushn: TODO need validation
      - jinja2>=3.1.2
      - bokeh==1.4.0 # dkushn: TODO not used, need update
      - plyfile==0.7.1 #dkushn: TODO critical, need to launch script that uses
      - trimesh==3.21.6
      - pycollada==0.6 # dkushn: not used
      - shapely==1.7.0 # dkushn: not used
      - wget==3.2
      - pypng==0.0.20
      - PyOpenGL==3.1.0
      - Cython==0.29.34
      - glumpy==1.2.0
      - ipdb==0.12.3
      - colorama==0.4.3
      - scikit-video==1.1.11
      - scikit-image==0.16.2
      - scikit-learn==1.2.3
      - pyyaml==5.1 # dkushn -- required
      - ipykernel==5.1.3
      - scipy==1.10.1
      - pywavefront==1.3.1
#      Jupyter(s) need to be checked
      - jupyter-client==8.2.0
      - jupyter-core==5.3.0
      - jupyter-server-proxy==1.5.0 # may be not required
      - jupyterlab==4.0.0
      - jupyterlab-server==2.22.1
      - seaborn=0.12.2
      - bokeh=3.1.1
